plugins {
    id 'application'
    id 'java'
}

group = 'com.umb'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

application {
    mainClass = 'com.umb.taller.Main'
}

tasks.test {
    useJUnitPlatform()
}

tasks.named('run') {
    standardInput = System.in
}